name: cron_checks

on:
  push:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: "Check URLs"
        run: |
          pip install -U requests
          ./scripts/check_urls.py
